# Generated by Django 2.1.8 on 2019-07-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogA', '0004_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
